// Generated by gencpp from file cohoma_detection/CoordinateTransformation.msg
// DO NOT EDIT!


#ifndef COHOMA_DETECTION_MESSAGE_COORDINATETRANSFORMATION_H
#define COHOMA_DETECTION_MESSAGE_COORDINATETRANSFORMATION_H

#include <ros/service_traits.h>


#include <cohoma_detection/CoordinateTransformationRequest.h>
#include <cohoma_detection/CoordinateTransformationResponse.h>


namespace cohoma_detection
{

struct CoordinateTransformation
{

typedef CoordinateTransformationRequest Request;
typedef CoordinateTransformationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CoordinateTransformation
} // namespace cohoma_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cohoma_detection::CoordinateTransformation > {
  static const char* value()
  {
    return "3064e8c447201208c1ba42ae35ce3d16";
  }

  static const char* value(const ::cohoma_detection::CoordinateTransformation&) { return value(); }
};

template<>
struct DataType< ::cohoma_detection::CoordinateTransformation > {
  static const char* value()
  {
    return "cohoma_detection/CoordinateTransformation";
  }

  static const char* value(const ::cohoma_detection::CoordinateTransformation&) { return value(); }
};


// service_traits::MD5Sum< ::cohoma_detection::CoordinateTransformationRequest> should match
// service_traits::MD5Sum< ::cohoma_detection::CoordinateTransformation >
template<>
struct MD5Sum< ::cohoma_detection::CoordinateTransformationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cohoma_detection::CoordinateTransformation >::value();
  }
  static const char* value(const ::cohoma_detection::CoordinateTransformationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cohoma_detection::CoordinateTransformationRequest> should match
// service_traits::DataType< ::cohoma_detection::CoordinateTransformation >
template<>
struct DataType< ::cohoma_detection::CoordinateTransformationRequest>
{
  static const char* value()
  {
    return DataType< ::cohoma_detection::CoordinateTransformation >::value();
  }
  static const char* value(const ::cohoma_detection::CoordinateTransformationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cohoma_detection::CoordinateTransformationResponse> should match
// service_traits::MD5Sum< ::cohoma_detection::CoordinateTransformation >
template<>
struct MD5Sum< ::cohoma_detection::CoordinateTransformationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cohoma_detection::CoordinateTransformation >::value();
  }
  static const char* value(const ::cohoma_detection::CoordinateTransformationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cohoma_detection::CoordinateTransformationResponse> should match
// service_traits::DataType< ::cohoma_detection::CoordinateTransformation >
template<>
struct DataType< ::cohoma_detection::CoordinateTransformationResponse>
{
  static const char* value()
  {
    return DataType< ::cohoma_detection::CoordinateTransformation >::value();
  }
  static const char* value(const ::cohoma_detection::CoordinateTransformationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COHOMA_DETECTION_MESSAGE_COORDINATETRANSFORMATION_H
