// Generated by gencpp from file cohoma_detection/CoordinateTransformationRequest.msg
// DO NOT EDIT!


#ifndef COHOMA_DETECTION_MESSAGE_COORDINATETRANSFORMATIONREQUEST_H
#define COHOMA_DETECTION_MESSAGE_COORDINATETRANSFORMATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>
#include <sensor_msgs/NavSatFix.h>

namespace cohoma_detection
{
template <class ContainerAllocator>
struct CoordinateTransformationRequest_
{
  typedef CoordinateTransformationRequest_<ContainerAllocator> Type;

  CoordinateTransformationRequest_()
    : translation()
    , rotation()
    , coor_pixel()
    , gps_drone()  {
    }
  CoordinateTransformationRequest_(const ContainerAllocator& _alloc)
    : translation(_alloc)
    , rotation(_alloc)
    , coor_pixel(_alloc)
    , gps_drone(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _translation_type;
  _translation_type translation;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rotation_type;
  _rotation_type rotation;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _coor_pixel_type;
  _coor_pixel_type coor_pixel;

   typedef  ::sensor_msgs::NavSatFix_<ContainerAllocator>  _gps_drone_type;
  _gps_drone_type gps_drone;





  typedef boost::shared_ptr< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CoordinateTransformationRequest_

typedef ::cohoma_detection::CoordinateTransformationRequest_<std::allocator<void> > CoordinateTransformationRequest;

typedef boost::shared_ptr< ::cohoma_detection::CoordinateTransformationRequest > CoordinateTransformationRequestPtr;
typedef boost::shared_ptr< ::cohoma_detection::CoordinateTransformationRequest const> CoordinateTransformationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator1> & lhs, const ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.translation == rhs.translation &&
    lhs.rotation == rhs.rotation &&
    lhs.coor_pixel == rhs.coor_pixel &&
    lhs.gps_drone == rhs.gps_drone;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator1> & lhs, const ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cohoma_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "537e25547db3dd9c62d41baa6668bb0f";
  }

  static const char* value(const ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x537e25547db3dd9cULL;
  static const uint64_t static_value2 = 0x62d41baa6668bb0fULL;
};

template<class ContainerAllocator>
struct DataType< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cohoma_detection/CoordinateTransformationRequest";
  }

  static const char* value(const ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 translation             # entre le repère de la caméra et le repère du monde réel\n"
"geometry_msgs/Vector3 rotation\n"
"geometry_msgs/Point   coor_pixel             # x et y coordonnées en pixel, on n'utilise pas z\n"
"sensor_msgs/NavSatFix gps_drone              # latitude longitude altitude ainsi que status header position_covariance du drone\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/NavSatFix\n"
"# Navigation Satellite fix for any Global Navigation Satellite System\n"
"#\n"
"# Specified using the WGS 84 reference ellipsoid\n"
"\n"
"# header.stamp specifies the ROS time for this measurement (the\n"
"#        corresponding satellite time may be reported using the\n"
"#        sensor_msgs/TimeReference message).\n"
"#\n"
"# header.frame_id is the frame of reference reported by the satellite\n"
"#        receiver, usually the location of the antenna.  This is a\n"
"#        Euclidean frame relative to the vehicle, not a reference\n"
"#        ellipsoid.\n"
"Header header\n"
"\n"
"# satellite fix status information\n"
"NavSatStatus status\n"
"\n"
"# Latitude [degrees]. Positive is north of equator; negative is south.\n"
"float64 latitude\n"
"\n"
"# Longitude [degrees]. Positive is east of prime meridian; negative is west.\n"
"float64 longitude\n"
"\n"
"# Altitude [m]. Positive is above the WGS 84 ellipsoid\n"
"# (quiet NaN if no altitude is available).\n"
"float64 altitude\n"
"\n"
"# Position covariance [m^2] defined relative to a tangential plane\n"
"# through the reported position. The components are East, North, and\n"
"# Up (ENU), in row-major order.\n"
"#\n"
"# Beware: this coordinate system exhibits singularities at the poles.\n"
"\n"
"float64[9] position_covariance\n"
"\n"
"# If the covariance of the fix is known, fill it in completely. If the\n"
"# GPS receiver provides the variance of each measurement, put them\n"
"# along the diagonal. If only Dilution of Precision is available,\n"
"# estimate an approximate covariance from that.\n"
"\n"
"uint8 COVARIANCE_TYPE_UNKNOWN = 0\n"
"uint8 COVARIANCE_TYPE_APPROXIMATED = 1\n"
"uint8 COVARIANCE_TYPE_DIAGONAL_KNOWN = 2\n"
"uint8 COVARIANCE_TYPE_KNOWN = 3\n"
"\n"
"uint8 position_covariance_type\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/NavSatStatus\n"
"# Navigation Satellite fix status for any Global Navigation Satellite System\n"
"\n"
"# Whether to output an augmented fix is determined by both the fix\n"
"# type and the last time differential corrections were received.  A\n"
"# fix is valid when status >= STATUS_FIX.\n"
"\n"
"int8 STATUS_NO_FIX =  -1        # unable to fix position\n"
"int8 STATUS_FIX =      0        # unaugmented fix\n"
"int8 STATUS_SBAS_FIX = 1        # with satellite-based augmentation\n"
"int8 STATUS_GBAS_FIX = 2        # with ground-based augmentation\n"
"\n"
"int8 status\n"
"\n"
"# Bits defining which Global Navigation Satellite System signals were\n"
"# used by the receiver.\n"
"\n"
"uint16 SERVICE_GPS =     1\n"
"uint16 SERVICE_GLONASS = 2\n"
"uint16 SERVICE_COMPASS = 4      # includes BeiDou.\n"
"uint16 SERVICE_GALILEO = 8\n"
"\n"
"uint16 service\n"
;
  }

  static const char* value(const ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.translation);
      stream.next(m.rotation);
      stream.next(m.coor_pixel);
      stream.next(m.gps_drone);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CoordinateTransformationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cohoma_detection::CoordinateTransformationRequest_<ContainerAllocator>& v)
  {
    s << indent << "translation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.translation);
    s << indent << "rotation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rotation);
    s << indent << "coor_pixel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.coor_pixel);
    s << indent << "gps_drone: ";
    s << std::endl;
    Printer< ::sensor_msgs::NavSatFix_<ContainerAllocator> >::stream(s, indent + "  ", v.gps_drone);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COHOMA_DETECTION_MESSAGE_COORDINATETRANSFORMATIONREQUEST_H
