// Generated by gencpp from file cohoma_detection/MissionContext.msg
// DO NOT EDIT!


#ifndef COHOMA_DETECTION_MESSAGE_MISSIONCONTEXT_H
#define COHOMA_DETECTION_MESSAGE_MISSIONCONTEXT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cohoma_detection/StrategicPoint.h>

namespace cohoma_detection
{
template <class ContainerAllocator>
struct MissionContext_
{
  typedef MissionContext_<ContainerAllocator> Type;

  MissionContext_()
    : header()
    , context_id()
    , strategic_points()  {
    }
  MissionContext_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , context_id(_alloc)
    , strategic_points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _context_id_type;
  _context_id_type context_id;

   typedef std::vector< ::cohoma_detection::StrategicPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cohoma_detection::StrategicPoint_<ContainerAllocator> >> _strategic_points_type;
  _strategic_points_type strategic_points;





  typedef boost::shared_ptr< ::cohoma_detection::MissionContext_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cohoma_detection::MissionContext_<ContainerAllocator> const> ConstPtr;

}; // struct MissionContext_

typedef ::cohoma_detection::MissionContext_<std::allocator<void> > MissionContext;

typedef boost::shared_ptr< ::cohoma_detection::MissionContext > MissionContextPtr;
typedef boost::shared_ptr< ::cohoma_detection::MissionContext const> MissionContextConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cohoma_detection::MissionContext_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cohoma_detection::MissionContext_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cohoma_detection::MissionContext_<ContainerAllocator1> & lhs, const ::cohoma_detection::MissionContext_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.context_id == rhs.context_id &&
    lhs.strategic_points == rhs.strategic_points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cohoma_detection::MissionContext_<ContainerAllocator1> & lhs, const ::cohoma_detection::MissionContext_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cohoma_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cohoma_detection::MissionContext_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cohoma_detection::MissionContext_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohoma_detection::MissionContext_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohoma_detection::MissionContext_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohoma_detection::MissionContext_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohoma_detection::MissionContext_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cohoma_detection::MissionContext_<ContainerAllocator> >
{
  static const char* value()
  {
    return "005f1c7be048bfb34caed7a413338cbd";
  }

  static const char* value(const ::cohoma_detection::MissionContext_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x005f1c7be048bfb3ULL;
  static const uint64_t static_value2 = 0x4caed7a413338cbdULL;
};

template<class ContainerAllocator>
struct DataType< ::cohoma_detection::MissionContext_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cohoma_detection/MissionContext";
  }

  static const char* value(const ::cohoma_detection::MissionContext_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cohoma_detection::MissionContext_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string context_id\n"
"cohoma_detection/StrategicPoint[] strategic_points\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: cohoma_detection/StrategicPoint\n"
"uint8 UNKNOWN=0\n"
"uint8 HYBRID=1\n"
"uint8 TERRESTRIAL=2\n"
"uint8 AERIAL=3\n"
"uint8 DEFUSED=0\n"
"uint8 ACTIVE=1\n"
"uint8 UNALTERABLE=2\n"
"string id\n"
"geographic_msgs/GeoPoint position\n"
"uint8 type\n"
"uint8 status\n"
"float32 radius\n"
"string message\n"
"================================================================================\n"
"MSG: geographic_msgs/GeoPoint\n"
"# Geographic point, using the WGS 84 reference ellipsoid.\n"
"\n"
"# Latitude [degrees]. Positive is north of equator; negative is south\n"
"# (-90 <= latitude <= +90).\n"
"float64 latitude\n"
"\n"
"# Longitude [degrees]. Positive is east of prime meridian; negative is\n"
"# west (-180 <= longitude <= +180). At the poles, latitude is -90 or\n"
"# +90, and longitude is irrelevant, but must be in range.\n"
"float64 longitude\n"
"\n"
"# Altitude [m]. Positive is above the WGS 84 ellipsoid (NaN if unspecified).\n"
"float64 altitude\n"
;
  }

  static const char* value(const ::cohoma_detection::MissionContext_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cohoma_detection::MissionContext_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.context_id);
      stream.next(m.strategic_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionContext_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cohoma_detection::MissionContext_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cohoma_detection::MissionContext_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "context_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.context_id);
    s << indent << "strategic_points[]" << std::endl;
    for (size_t i = 0; i < v.strategic_points.size(); ++i)
    {
      s << indent << "  strategic_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cohoma_detection::StrategicPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.strategic_points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COHOMA_DETECTION_MESSAGE_MISSIONCONTEXT_H
