// Generated by gencpp from file cohoma_detection/TrapDeleteRequest.msg
// DO NOT EDIT!


#ifndef COHOMA_DETECTION_MESSAGE_TRAPDELETEREQUEST_H
#define COHOMA_DETECTION_MESSAGE_TRAPDELETEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cohoma_detection
{
template <class ContainerAllocator>
struct TrapDeleteRequest_
{
  typedef TrapDeleteRequest_<ContainerAllocator> Type;

  TrapDeleteRequest_()
    : delete_index(0)  {
    }
  TrapDeleteRequest_(const ContainerAllocator& _alloc)
    : delete_index(0)  {
  (void)_alloc;
    }



   typedef int8_t _delete_index_type;
  _delete_index_type delete_index;





  typedef boost::shared_ptr< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TrapDeleteRequest_

typedef ::cohoma_detection::TrapDeleteRequest_<std::allocator<void> > TrapDeleteRequest;

typedef boost::shared_ptr< ::cohoma_detection::TrapDeleteRequest > TrapDeleteRequestPtr;
typedef boost::shared_ptr< ::cohoma_detection::TrapDeleteRequest const> TrapDeleteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator1> & lhs, const ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator2> & rhs)
{
  return lhs.delete_index == rhs.delete_index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator1> & lhs, const ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cohoma_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2365dc8a72132b8e6b7080d7b832d42";
  }

  static const char* value(const ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2365dc8a72132b8ULL;
  static const uint64_t static_value2 = 0xe6b7080d7b832d42ULL;
};

template<class ContainerAllocator>
struct DataType< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cohoma_detection/TrapDeleteRequest";
  }

  static const char* value(const ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 delete_index\n"
;
  }

  static const char* value(const ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.delete_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrapDeleteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cohoma_detection::TrapDeleteRequest_<ContainerAllocator>& v)
  {
    s << indent << "delete_index: ";
    Printer<int8_t>::stream(s, indent + "  ", v.delete_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COHOMA_DETECTION_MESSAGE_TRAPDELETEREQUEST_H
