// Generated by gencpp from file cohoma_detection/TrapDisable.msg
// DO NOT EDIT!


#ifndef COHOMA_DETECTION_MESSAGE_TRAPDISABLE_H
#define COHOMA_DETECTION_MESSAGE_TRAPDISABLE_H

#include <ros/service_traits.h>


#include <cohoma_detection/TrapDisableRequest.h>
#include <cohoma_detection/TrapDisableResponse.h>


namespace cohoma_detection
{

struct TrapDisable
{

typedef TrapDisableRequest Request;
typedef TrapDisableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrapDisable
} // namespace cohoma_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cohoma_detection::TrapDisable > {
  static const char* value()
  {
    return "6bf05e5158bcedad8548df9e0c97322b";
  }

  static const char* value(const ::cohoma_detection::TrapDisable&) { return value(); }
};

template<>
struct DataType< ::cohoma_detection::TrapDisable > {
  static const char* value()
  {
    return "cohoma_detection/TrapDisable";
  }

  static const char* value(const ::cohoma_detection::TrapDisable&) { return value(); }
};


// service_traits::MD5Sum< ::cohoma_detection::TrapDisableRequest> should match
// service_traits::MD5Sum< ::cohoma_detection::TrapDisable >
template<>
struct MD5Sum< ::cohoma_detection::TrapDisableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cohoma_detection::TrapDisable >::value();
  }
  static const char* value(const ::cohoma_detection::TrapDisableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cohoma_detection::TrapDisableRequest> should match
// service_traits::DataType< ::cohoma_detection::TrapDisable >
template<>
struct DataType< ::cohoma_detection::TrapDisableRequest>
{
  static const char* value()
  {
    return DataType< ::cohoma_detection::TrapDisable >::value();
  }
  static const char* value(const ::cohoma_detection::TrapDisableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cohoma_detection::TrapDisableResponse> should match
// service_traits::MD5Sum< ::cohoma_detection::TrapDisable >
template<>
struct MD5Sum< ::cohoma_detection::TrapDisableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cohoma_detection::TrapDisable >::value();
  }
  static const char* value(const ::cohoma_detection::TrapDisableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cohoma_detection::TrapDisableResponse> should match
// service_traits::DataType< ::cohoma_detection::TrapDisable >
template<>
struct DataType< ::cohoma_detection::TrapDisableResponse>
{
  static const char* value()
  {
    return DataType< ::cohoma_detection::TrapDisable >::value();
  }
  static const char* value(const ::cohoma_detection::TrapDisableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COHOMA_DETECTION_MESSAGE_TRAPDISABLE_H
