// Generated by gencpp from file cohoma_detection/TrapDelete.msg
// DO NOT EDIT!


#ifndef COHOMA_DETECTION_MESSAGE_TRAPDELETE_H
#define COHOMA_DETECTION_MESSAGE_TRAPDELETE_H

#include <ros/service_traits.h>


#include <cohoma_detection/TrapDeleteRequest.h>
#include <cohoma_detection/TrapDeleteResponse.h>


namespace cohoma_detection
{

struct TrapDelete
{

typedef TrapDeleteRequest Request;
typedef TrapDeleteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrapDelete
} // namespace cohoma_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cohoma_detection::TrapDelete > {
  static const char* value()
  {
    return "9dd0896216c2e4f68d45b72eb2896fe8";
  }

  static const char* value(const ::cohoma_detection::TrapDelete&) { return value(); }
};

template<>
struct DataType< ::cohoma_detection::TrapDelete > {
  static const char* value()
  {
    return "cohoma_detection/TrapDelete";
  }

  static const char* value(const ::cohoma_detection::TrapDelete&) { return value(); }
};


// service_traits::MD5Sum< ::cohoma_detection::TrapDeleteRequest> should match
// service_traits::MD5Sum< ::cohoma_detection::TrapDelete >
template<>
struct MD5Sum< ::cohoma_detection::TrapDeleteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cohoma_detection::TrapDelete >::value();
  }
  static const char* value(const ::cohoma_detection::TrapDeleteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cohoma_detection::TrapDeleteRequest> should match
// service_traits::DataType< ::cohoma_detection::TrapDelete >
template<>
struct DataType< ::cohoma_detection::TrapDeleteRequest>
{
  static const char* value()
  {
    return DataType< ::cohoma_detection::TrapDelete >::value();
  }
  static const char* value(const ::cohoma_detection::TrapDeleteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cohoma_detection::TrapDeleteResponse> should match
// service_traits::MD5Sum< ::cohoma_detection::TrapDelete >
template<>
struct MD5Sum< ::cohoma_detection::TrapDeleteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cohoma_detection::TrapDelete >::value();
  }
  static const char* value(const ::cohoma_detection::TrapDeleteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cohoma_detection::TrapDeleteResponse> should match
// service_traits::DataType< ::cohoma_detection::TrapDelete >
template<>
struct DataType< ::cohoma_detection::TrapDeleteResponse>
{
  static const char* value()
  {
    return DataType< ::cohoma_detection::TrapDelete >::value();
  }
  static const char* value(const ::cohoma_detection::TrapDeleteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COHOMA_DETECTION_MESSAGE_TRAPDELETE_H
