// Generated by gencpp from file cohoma_detection/TrapDisableResponse.msg
// DO NOT EDIT!


#ifndef COHOMA_DETECTION_MESSAGE_TRAPDISABLERESPONSE_H
#define COHOMA_DETECTION_MESSAGE_TRAPDISABLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cohoma_detection
{
template <class ContainerAllocator>
struct TrapDisableResponse_
{
  typedef TrapDisableResponse_<ContainerAllocator> Type;

  TrapDisableResponse_()
    : success(false)  {
    }
  TrapDisableResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TrapDisableResponse_

typedef ::cohoma_detection::TrapDisableResponse_<std::allocator<void> > TrapDisableResponse;

typedef boost::shared_ptr< ::cohoma_detection::TrapDisableResponse > TrapDisableResponsePtr;
typedef boost::shared_ptr< ::cohoma_detection::TrapDisableResponse const> TrapDisableResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cohoma_detection::TrapDisableResponse_<ContainerAllocator1> & lhs, const ::cohoma_detection::TrapDisableResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cohoma_detection::TrapDisableResponse_<ContainerAllocator1> & lhs, const ::cohoma_detection::TrapDisableResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cohoma_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::cohoma_detection::TrapDisableResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cohoma_detection/TrapDisableResponse";
  }

  static const char* value(const ::cohoma_detection::TrapDisableResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::cohoma_detection::TrapDisableResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrapDisableResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cohoma_detection::TrapDisableResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cohoma_detection::TrapDisableResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COHOMA_DETECTION_MESSAGE_TRAPDISABLERESPONSE_H
