# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cohoma_detection/CoordinateTransformationRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import sensor_msgs.msg
import std_msgs.msg

class CoordinateTransformationRequest(genpy.Message):
  _md5sum = "537e25547db3dd9c62d41baa6668bb0f"
  _type = "cohoma_detection/CoordinateTransformationRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Vector3 translation             # entre le repère de la caméra et le repère du monde réel
geometry_msgs/Vector3 rotation
geometry_msgs/Point   coor_pixel             # x et y coordonnées en pixel, on n'utilise pas z
sensor_msgs/NavSatFix gps_drone              # latitude longitude altitude ainsi que status header position_covariance du drone

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: sensor_msgs/NavSatFix
# Navigation Satellite fix for any Global Navigation Satellite System
#
# Specified using the WGS 84 reference ellipsoid

# header.stamp specifies the ROS time for this measurement (the
#        corresponding satellite time may be reported using the
#        sensor_msgs/TimeReference message).
#
# header.frame_id is the frame of reference reported by the satellite
#        receiver, usually the location of the antenna.  This is a
#        Euclidean frame relative to the vehicle, not a reference
#        ellipsoid.
Header header

# satellite fix status information
NavSatStatus status

# Latitude [degrees]. Positive is north of equator; negative is south.
float64 latitude

# Longitude [degrees]. Positive is east of prime meridian; negative is west.
float64 longitude

# Altitude [m]. Positive is above the WGS 84 ellipsoid
# (quiet NaN if no altitude is available).
float64 altitude

# Position covariance [m^2] defined relative to a tangential plane
# through the reported position. The components are East, North, and
# Up (ENU), in row-major order.
#
# Beware: this coordinate system exhibits singularities at the poles.

float64[9] position_covariance

# If the covariance of the fix is known, fill it in completely. If the
# GPS receiver provides the variance of each measurement, put them
# along the diagonal. If only Dilution of Precision is available,
# estimate an approximate covariance from that.

uint8 COVARIANCE_TYPE_UNKNOWN = 0
uint8 COVARIANCE_TYPE_APPROXIMATED = 1
uint8 COVARIANCE_TYPE_DIAGONAL_KNOWN = 2
uint8 COVARIANCE_TYPE_KNOWN = 3

uint8 position_covariance_type

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: sensor_msgs/NavSatStatus
# Navigation Satellite fix status for any Global Navigation Satellite System

# Whether to output an augmented fix is determined by both the fix
# type and the last time differential corrections were received.  A
# fix is valid when status >= STATUS_FIX.

int8 STATUS_NO_FIX =  -1        # unable to fix position
int8 STATUS_FIX =      0        # unaugmented fix
int8 STATUS_SBAS_FIX = 1        # with satellite-based augmentation
int8 STATUS_GBAS_FIX = 2        # with ground-based augmentation

int8 status

# Bits defining which Global Navigation Satellite System signals were
# used by the receiver.

uint16 SERVICE_GPS =     1
uint16 SERVICE_GLONASS = 2
uint16 SERVICE_COMPASS = 4      # includes BeiDou.
uint16 SERVICE_GALILEO = 8

uint16 service
"""
  __slots__ = ['translation','rotation','coor_pixel','gps_drone']
  _slot_types = ['geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Point','sensor_msgs/NavSatFix']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       translation,rotation,coor_pixel,gps_drone

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CoordinateTransformationRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.translation is None:
        self.translation = geometry_msgs.msg.Vector3()
      if self.rotation is None:
        self.rotation = geometry_msgs.msg.Vector3()
      if self.coor_pixel is None:
        self.coor_pixel = geometry_msgs.msg.Point()
      if self.gps_drone is None:
        self.gps_drone = sensor_msgs.msg.NavSatFix()
    else:
      self.translation = geometry_msgs.msg.Vector3()
      self.rotation = geometry_msgs.msg.Vector3()
      self.coor_pixel = geometry_msgs.msg.Point()
      self.gps_drone = sensor_msgs.msg.NavSatFix()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9d3I().pack(_x.translation.x, _x.translation.y, _x.translation.z, _x.rotation.x, _x.rotation.y, _x.rotation.z, _x.coor_pixel.x, _x.coor_pixel.y, _x.coor_pixel.z, _x.gps_drone.header.seq, _x.gps_drone.header.stamp.secs, _x.gps_drone.header.stamp.nsecs))
      _x = self.gps_drone.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_bH3d().pack(_x.gps_drone.status.status, _x.gps_drone.status.service, _x.gps_drone.latitude, _x.gps_drone.longitude, _x.gps_drone.altitude))
      buff.write(_get_struct_9d().pack(*self.gps_drone.position_covariance))
      _x = self.gps_drone.position_covariance_type
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.translation is None:
        self.translation = geometry_msgs.msg.Vector3()
      if self.rotation is None:
        self.rotation = geometry_msgs.msg.Vector3()
      if self.coor_pixel is None:
        self.coor_pixel = geometry_msgs.msg.Point()
      if self.gps_drone is None:
        self.gps_drone = sensor_msgs.msg.NavSatFix()
      end = 0
      _x = self
      start = end
      end += 84
      (_x.translation.x, _x.translation.y, _x.translation.z, _x.rotation.x, _x.rotation.y, _x.rotation.z, _x.coor_pixel.x, _x.coor_pixel.y, _x.coor_pixel.z, _x.gps_drone.header.seq, _x.gps_drone.header.stamp.secs, _x.gps_drone.header.stamp.nsecs,) = _get_struct_9d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gps_drone.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.gps_drone.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 27
      (_x.gps_drone.status.status, _x.gps_drone.status.service, _x.gps_drone.latitude, _x.gps_drone.longitude, _x.gps_drone.altitude,) = _get_struct_bH3d().unpack(str[start:end])
      start = end
      end += 72
      self.gps_drone.position_covariance = _get_struct_9d().unpack(str[start:end])
      start = end
      end += 1
      (self.gps_drone.position_covariance_type,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9d3I().pack(_x.translation.x, _x.translation.y, _x.translation.z, _x.rotation.x, _x.rotation.y, _x.rotation.z, _x.coor_pixel.x, _x.coor_pixel.y, _x.coor_pixel.z, _x.gps_drone.header.seq, _x.gps_drone.header.stamp.secs, _x.gps_drone.header.stamp.nsecs))
      _x = self.gps_drone.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_bH3d().pack(_x.gps_drone.status.status, _x.gps_drone.status.service, _x.gps_drone.latitude, _x.gps_drone.longitude, _x.gps_drone.altitude))
      buff.write(self.gps_drone.position_covariance.tostring())
      _x = self.gps_drone.position_covariance_type
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.translation is None:
        self.translation = geometry_msgs.msg.Vector3()
      if self.rotation is None:
        self.rotation = geometry_msgs.msg.Vector3()
      if self.coor_pixel is None:
        self.coor_pixel = geometry_msgs.msg.Point()
      if self.gps_drone is None:
        self.gps_drone = sensor_msgs.msg.NavSatFix()
      end = 0
      _x = self
      start = end
      end += 84
      (_x.translation.x, _x.translation.y, _x.translation.z, _x.rotation.x, _x.rotation.y, _x.rotation.z, _x.coor_pixel.x, _x.coor_pixel.y, _x.coor_pixel.z, _x.gps_drone.header.seq, _x.gps_drone.header.stamp.secs, _x.gps_drone.header.stamp.nsecs,) = _get_struct_9d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gps_drone.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.gps_drone.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 27
      (_x.gps_drone.status.status, _x.gps_drone.status.service, _x.gps_drone.latitude, _x.gps_drone.longitude, _x.gps_drone.altitude,) = _get_struct_bH3d().unpack(str[start:end])
      start = end
      end += 72
      self.gps_drone.position_covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      start = end
      end += 1
      (self.gps_drone.position_covariance_type,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
_struct_9d3I = None
def _get_struct_9d3I():
    global _struct_9d3I
    if _struct_9d3I is None:
        _struct_9d3I = struct.Struct("<9d3I")
    return _struct_9d3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_bH3d = None
def _get_struct_bH3d():
    global _struct_bH3d
    if _struct_bH3d is None:
        _struct_bH3d = struct.Struct("<bH3d")
    return _struct_bH3d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cohoma_detection/CoordinateTransformationResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geographic_msgs.msg

class CoordinateTransformationResponse(genpy.Message):
  _md5sum = "70f4fc60fa0596961886b4f4cc362f6b"
  _type = "cohoma_detection/CoordinateTransformationResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geographic_msgs/GeoPoint gps_qrcode          # latitude longitude altitude

# to modify completely!!!!

================================================================================
MSG: geographic_msgs/GeoPoint
# Geographic point, using the WGS 84 reference ellipsoid.

# Latitude [degrees]. Positive is north of equator; negative is south
# (-90 <= latitude <= +90).
float64 latitude

# Longitude [degrees]. Positive is east of prime meridian; negative is
# west (-180 <= longitude <= +180). At the poles, latitude is -90 or
# +90, and longitude is irrelevant, but must be in range.
float64 longitude

# Altitude [m]. Positive is above the WGS 84 ellipsoid (NaN if unspecified).
float64 altitude
"""
  __slots__ = ['gps_qrcode']
  _slot_types = ['geographic_msgs/GeoPoint']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gps_qrcode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CoordinateTransformationResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.gps_qrcode is None:
        self.gps_qrcode = geographic_msgs.msg.GeoPoint()
    else:
      self.gps_qrcode = geographic_msgs.msg.GeoPoint()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d().pack(_x.gps_qrcode.latitude, _x.gps_qrcode.longitude, _x.gps_qrcode.altitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.gps_qrcode is None:
        self.gps_qrcode = geographic_msgs.msg.GeoPoint()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.gps_qrcode.latitude, _x.gps_qrcode.longitude, _x.gps_qrcode.altitude,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d().pack(_x.gps_qrcode.latitude, _x.gps_qrcode.longitude, _x.gps_qrcode.altitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.gps_qrcode is None:
        self.gps_qrcode = geographic_msgs.msg.GeoPoint()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.gps_qrcode.latitude, _x.gps_qrcode.longitude, _x.gps_qrcode.altitude,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
class CoordinateTransformation(object):
  _type          = 'cohoma_detection/CoordinateTransformation'
  _md5sum = '3064e8c447201208c1ba42ae35ce3d16'
  _request_class  = CoordinateTransformationRequest
  _response_class = CoordinateTransformationResponse
