(cl:defpackage cohoma_detection-srv
  (:use )
  (:export
   "COORDINATETRANSFORMATION"
   "<COORDINATETRANSFORMATION-REQUEST>"
   "COORDINATETRANSFORMATION-REQUEST"
   "<COORDINATETRANSFORMATION-RESPONSE>"
   "COORDINATETRANSFORMATION-RESPONSE"
   "PUSHSP"
   "<PUSHSP-REQUEST>"
   "PUSHSP-REQUEST"
   "<PUSHSP-RESPONSE>"
   "PUSHSP-RESPONSE"
   "TRAPDELETE"
   "<TRAPDELETE-REQUEST>"
   "TRAPDELETE-REQUEST"
   "<TRAPDELETE-RESPONSE>"
   "TRAPDELETE-RESPONSE"
   "TRAPDISABLE"
   "<TRAPDISABLE-REQUEST>"
   "TRAPDISABLE-REQUEST"
   "<TRAPDISABLE-RESPONSE>"
   "TRAPDISABLE-RESPONSE"
  ))

